# 定数(スクリーン)
SCREEN_WIDTH = 160  
SCREEN_HEIGHT = 120

# 定数(プレイヤー)
START_PLAYER_POSX = 40
START_PLAYER_POSY = 90
PLAYER_FALL_SPEED = 1
PLAYER_MOVE_SPEED = 1

# 定数(棒)
STICK_WIDTH = 2
STICK_DEFAULT_LENGTH = 10    # 棒の初期長さ
STICK_GROWTH_SPEED = 1       # 棒の伸びる早さ
STICK_MAX_LENGTH = 90      # 棒の伸び上限
STICK_SPIN_DEGREE = 90       # 棒の回転角度
STICK_SPIN_TOTAL_FRAME = 10  # 棒の回転にかかるフレーム数

# 定数(床)
GROUND_OFFSET = 1            # 地面の位置調整
GROUND_HEIGHT = START_PLAYER_POSY + GROUND_OFFSET
FLOOR_X_MAX = START_PLAYER_POSX + STICK_MAX_LENGTH
NEXT_FLOOR_MIN_DISTANCE = 20

# 定数(全オブジェクト移動用)
ALL_OBJECTS_MOVE_SPEED = 2

# 定数(ゲームURL)
GAME_URL = None


# シーン
TITLE_SCENE = "title"

PLAY_SCENE = "play"
