# 定数(スクリーン)
SCREEN_WIDTH = 160  
SCREEN_HEIGHT = 120

# 定数(プレイヤー)
START_PLAYER_POSX = 40
START_PLAYER_POSY = 90
PLAYER_FALL_SPEED = 1
PLAYER_MOVE_SPEED = 1

# 定数(棒)
STICK_WIDTH = 2
STICK_DEFAULT_LENGTH = 10    # 棒の初期長さ
STICK_GROWTH_SPEED = 1       # 棒の伸びる早さ
STICK_MAX_LENGTH = 90      # 棒の伸び上限

# 定数(床)
GROUND_OFFSET = 1            # 地面の位置調整
GROUND_HEIGHT = START_PLAYER_POSY + GROUND_OFFSET


# シーン
TITLE_SCENE = "title"

PLAY_SCENE = "play"
